In [3]:
!pip install torch cuda

In [4]:
# torch 만 깔면, cpu를 활용하고, torch cuda는 그래픽카드를 활용하여 연산을 가속해줌.

In [5]:
# CPU(Central Processing Unit 중앙처리장치) - 정수형
# 내 컴퓨터의 경우, 코어 개수는 12개, 2.2GHz
# RAM(Random Access Memory 중앙기억장치)
# 그래픽카드(AMD, nVidia) - GPU, RAM 픽셀처리(실수형)
# nVidia GTX1060 1200개, 1.5Hhz

In [15]:
import torch
import numpy as np

In [37]:
torch.__version__

'1.9.0+cpu'

In [38]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [39]:
np_array = np.array(data)
np_data = torch.from_numpy(np_array)

In [40]:
x_data

tensor([[1, 2],
        [3, 4]])

In [41]:
np_data

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [50]:
t1 = torch.FloatTensor([[1, 3]])
t2 = torch.FloatTensor([[2, 4]])
print(t1 + t2)

tensor([[3., 7.]])


In [51]:
x_data_f.mean()

NameError: name 'x_data_f' is not defined

In [52]:
x_data_f.mean(dim = 0)

NameError: name 'x_data_f' is not defined

In [53]:
x_data_f.mean(dim = 1)

NameError: name 'x_data_f' is not defined

In [54]:
torch.cat([t1, t2], dim = 0)  # 열 방향으로 합치(concatenate)

tensor([[1., 3.],
        [2., 4.]])

In [55]:
torch.cat([t1, t2], dim = 1)   # 행 방향으로 합치(concatenate)

tensor([[1., 3., 2., 4.]])

In [56]:
t3= torch.FloatTensor([5, 6])
torch.stack([t1, t2, t3])

RuntimeError: stack expects each tensor to be equal size, but got [1, 2] at entry 0 and [2] at entry 2

In [ ]:
# 1 -> 2
# 2 -> 3
# 3 -> 6
# y = 2x

In [58]:
X_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[4], [5], [6]])

In [61]:
# 가설 설정
# y = W*x + b
# 기존 머신러닝 : MSE 평균제곱오차
# cost function(비용함수) = loss function(손실함수) 
# error function(오차 함수) = objective function(목적 함수)
# 옵티마이저는 경사하강법(Gradient Descent)을 사용 {Ex. 머신러닝에서 fit.}

In [65]:
import torch.nn as nn
import torch.nn.functional as F
X_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
model = nn.Linear(1, 1) #(input_dim = 1, output_dim = 1)
print(list(model.parameters()))
optimizer = optim.SGD(model.parameters(), lr = 0.01)

np_epochs = 2000
for epoch in range(nb_epochs+1):
    prediction = model(X_train)
    cost = F.mse_loss(prediction, y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 100 == 0:
        print('Epoch{:4d}/{} loss:{:5f}'.format(
            epoch, nb_epochs, cost.item()))

[Parameter containing:
tensor([[-0.8887]], requires_grad=True), Parameter containing:
tensor([0.0720], requires_grad=True)]


NameError: name 'optim' is not defined