In [1]:
# 전처리 할 때 유용하게 사용할 수 있는 방법.

def positive(l):
    result = []
    for i in l:
        if i > 0 : result.append(i)
    return result

print(positive([1, -3, 2, 0, -5, 6]))

[1, 2, 6]


In [4]:
def positive(x):
    return x > 0
data = [1, -3, 2, 0, -5, 6]
f = filter(positive, data)
print(list(f))

[1, 2, 6]


In [6]:
data = [1, -3, 2, 0, -5, 6]
list(filter(lambda x: x > 0, data))

[1, 2, 6]

In [7]:
a, b = input("숫자 두개를 입력하세요").split()
a = int(a)
b = int(b)
print(a+1 ,"그리고", b+1)

숫자 두개를 입력하세요10 20
11 그리고 21


In [8]:
data1 = [1, 2, 3]
data2 = [4, 5, 6]
list(zip(data1, data2))

[(1, 4), (2, 5), (3, 6)]

In [12]:
data1 = [1, 2, 3]
data2 = [4, 5, 6]
data3 = [7, 8, 9]
list(zip(data1, data2, data3))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [14]:
import os
os.environ["path"]

'C:\\ProgramData\\Anaconda3;C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin;C:\\ProgramData\\Anaconda3\\Library\\usr\\bin;C:\\ProgramData\\Anaconda3\\Library\\bin;C:\\ProgramData\\Anaconda3\\Scripts;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\Git\\cmd;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\W

In [16]:
os.getcwd()

'C:\\workspace\\Python'

In [22]:
import glob
glob.glob('C:\\workspace\\Python\\*.py')

['C:\\workspace\\Python\\mod1.py', 'C:\\workspace\\Python\\mod2.py']

In [24]:
import time
time.time()

1622012864.3320343

In [30]:
time.localtime(time.time())

time.struct_time(tm_year=2021, tm_mon=5, tm_mday=26, tm_hour=16, tm_min=8, tm_sec=20, tm_wday=2, tm_yday=146, tm_isdst=0)

In [32]:
time.asctime(time.localtime(time.time())).split()

['Wed', 'May', '26', '16:09:35', '2021']

In [33]:
for i in range(10):
    print(i)
    time.sleep(1)

0
1
2
3
4
5
6
7
8
9


In [36]:
import random
random.random()

0.44182615252788904

In [38]:
random.randint(1, 45)

26


In [48]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for i in range(10): my_arr2 = my_arr*2

Wall time: 15 ms


In [49]:
%time for i in range(10): my_list2 =[x * 2 for x in my_list]

Wall time: 713 ms


In [47]:
713/15    # 일반 파이썬 코드로 돌리는 것과 Numpy로 돌리는 것과는 처리시간 차이가 50배 가까이 난다.
# Numpy를 사용하는 이유 => 속도 때문!!

47.53333333333333

In [51]:
# 데이터 랜덤으로 생성
data = np.random.randn(2, 3)
data

array([[-1.78873051,  0.30170878, -0.24970068],
       [-1.49243219, -2.33222004, -1.15513136]])

In [52]:
data * 10

array([[-17.88730506,   3.01708778,  -2.49700676],
       [-14.92432195, -23.32220041, -11.55131365]])

In [53]:
data + data

array([[-3.57746101,  0.60341756, -0.49940135],
       [-2.98486439, -4.66444008, -2.31026273]])

In [55]:
data.shape          # 2행 3열의 모양.

(2, 3)

In [56]:
data.dtype     # float는 실수형.

dtype('float64')

In [58]:
# 리스트로 array 생성하기
# 리스트에 실수와 정수를 섞어 두면, np.array함수는 "모든 요소를 같은 형식으로" 배열을 생성한다.
data = [6, 7.5, 8, 0, 1]
arr = np.array(data)
arr                        # 모든 요소가 실수로 되어 있음.

array([6. , 7.5, 8. , 0. , 1. ])

In [ ]:
data = [6, 7.5, 8, 0, 1]
arr = np.array(data)
arr

In [59]:
data2d = [[1, 2, 3, 4], [5, 6, 7, 8]]
data2d

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [60]:
arr2d = np.array(data2d)

In [61]:
arr2d.ndim

2

In [62]:
arr2d.shape

(2, 4)

이것은 마크다운 인가요? 줄을 잡고 "m"누르면 마크다운 되는군용

In [64]:
np.zeros(10)    # 빈 배열 만들기(R에서의 data.frame이랑 비슷한 개념일듯...??)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [66]:
np.zeros((3, 6))         # 괄호가 두 개인 이유: zeros는 하나의 값만 받아들인다. 따라서 (3, 6)이라는 하나의 튜플값을 입력.

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [67]:
np.zeros((2, 3, 2))     # 2층으로 나눈 뒤, 거기에 3행 2열 배열을 넣어 줌.

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [68]:
np.zeros((2, 3, 2)).dtype     # numpy 타입이 실수인 이유 => gpu사용한 연산을 하기 때문에, 병렬연산인 gpu에서는 실수형이 더 빠르다.(사실 무슨말인지 이해하지 못했다. ㅠㅠ)

dtype('float64')

In [70]:
arr = np.zeros((2, 3, 2), dtype = np.int32)
arr.dtype

dtype('int32')

In [72]:
arr1 = np.zeros((2, 3))
arr2 = np.ones_like(arr1)
arr2.shape
arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [73]:
arr3 = np.full((2, 3), 5)     # np.full => 특정한 숫자로 배열을 채우고 싶을 때.
arr3

array([[5, 5, 5],
       [5, 5, 5]])

In [76]:
arr4 = np.eye(3)            # np.eye => 단위행렬 만들 때.
arr4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])